# Generated by Django 4.0.4 on 2022-05-03 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ether_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)], verbose_name='Holder')),
                ('value', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)], verbose_name='Value')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)], verbose_name='Holder')),
                ('value', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)], verbose_name='Value')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)], verbose_name='Holder')),
                ('value', models.CharField(max_length=42, validators=[django.core.validators.MinLengthValidator(42)], verbose_name='Value')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.AddField(
            model_name='income',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
