# Generated by Django 4.0.4 on 2022-05-07 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ether_events', '0002_incomedaily_incomemonthly_incomeweekly_income_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='IncomeDaily',
        ),
        migrations.DeleteModel(
            name='IncomeMonthly',
        ),
        migrations.DeleteModel(
            name='IncomeWeekly',
        ),
    ]
